pipeline {
    agent { docker { image 'node:6.3' } }
    stages {
        stage('build') {
            steps {
                sh 'ls'
                sh 'cat /etc/mysql/my.cnf'
                sh 'npm --version'
            }
        }
    }
}
