pipeline {
    agent { docker { image 'node:6.3' } }
    stages {
        stage('build') {
            steps {
                dir('subdir') {
                    sh 'ls'
                    sh 'cat /etc/mysql/my.cnf'
                    sh 'echo "hi" > me_there'
                }
            }
        }
        stage('next stage') {
            steps {
                sh 'cat me_there'
            }
        }
    }
}
